export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    profile: '/auth/profile',
    register: '/auth/register',
  },
  admin: {
    dashboard: '/admin/dashboard',
    stores: '/admin/stores',
    pendingStores: '/admin/stores/pending',
    approveStore: (id: string) => `/admin/stores/${id}/approve`,
    rejectStore: (id: string) => `/admin/stores/${id}/reject`,
    suspendStore: (id: string) => `/admin/stores/${id}/suspend`,
    users: '/admin/users',
    userDetails: (id: string) => `/admin/users/${id}`,
    subscriptions: '/admin/subscriptions',
    cancelSubscription: (id: string) => `/admin/subscriptions/${id}/cancel`,
    updateSubscription: (id: string) => `/admin/subscriptions/${id}`,
    orders: '/admin/orders',
    plans: '/plans/all',
    createPlan: '/plans',
    updatePlan: (id: string) => `/plans/${id}`,
    deletePlan: (id: string) => `/plans/${id}`,
  },
} as const;
