export const API_ROUTES = {
  auth: {
    login: '/auth/login',
    logout: '/auth/logout',
    profile: '/auth/profile',
    register: '/auth/register',
  },
  stores: {
    base: '/stores',
    details: (id: string) => `/stores/${id}`,
    bySlug: (slug: string) => `/stores/slug/${slug}`,
    my: '/stores/my',
    products: (storeId: string) => `/stores/${storeId}/products`,
    orders: (storeId: string) => `/stores/${storeId}/orders`,
    subscription: (id: string) => `/stores/${id}/subscription`,
    cancelSubscription: (id: string) => `/stores/${id}/subscription/cancel`,
    upgradeSubscription: (id: string) => `/stores/${id}/subscription/upgrade`,
    limits: (id: string) => `/stores/${id}/limits`,
  },
  products: {
    base: '/products',
    my: '/products/my',
    details: (id: string) => `/products/${id}`,
    bySku: (sku: string) => `/products/sku/${sku}`,
    inventory: (id: string) => `/products/${id}/inventory`,
    toggleStatus: (id: string) => `/products/${id}/toggle-status`,
  },
  cart: {
    base: '/storefront/cart',
    items: '/storefront/cart/items',
    item: (itemId: string) => `/storefront/cart/items/${itemId}`,
    checkout: '/storefront/checkout',
  },
  orders: {
    base: '/orders',
    details: (id: string) => `/orders/${id}`,
    status: (id: string) => `/orders/${id}/status`,
    all: '/orders/all',
    seller: '/orders/seller',
    store: (storeId: string) => `/orders/store/${storeId}`,
  },
  reviews: {
    base: (productId: string) => `/reviews/${productId}`,
    product: (productId: string) => `/reviews/product/${productId}`,
    stats: (productId: string) => `/reviews/product/${productId}/stats`,
    my: '/reviews/my',
    details: (id: string) => `/reviews/${id}`,
    helpful: (id: string) => `/reviews/${id}/helpful`,
    canReview: (productId: string) => `/reviews/${productId}/can-review`,
  },
  categories: {
    base: '/categories',
    bySlug: (slug: string) => `/categories/${slug}`,
  },
  plans: {
    base: '/plans',
    details: (id: string) => `/plans/${id}`,
  },
  payments: {
    initiate: '/payments/initiate',
    refund: '/payments/refund',
    webhooks: (provider: string) => `/payments/webhooks/${provider}`,
  },
  inventory: {
    locations: '/inventory/locations',
    levels: '/inventory/levels',
    adjust: '/inventory/adjust',
  },
  webhooks: {
    base: '/webhooks',
    details: (id: string) => `/webhooks/${id}`,
  },
  themes: {
    published: '/themes/published',
    store: (storeId: string) => `/themes/store/${storeId}`,
    details: (id: string) => `/themes/${id}`,
    publish: (id: string) => `/themes/${id}/publish`,
  },
  staff: {
    list: (storeId: string) => `/staff/${storeId}`,
    invite: (storeId: string) => `/staff/${storeId}/invite`,
  },
  domains: {
    check: '/domains/check',
    request: (storeId: string) => `/domains/store/${storeId}/request`,
  },
  assets: {
    list: (storeId: string) => `/assets/${storeId}`,
    upload: (storeId: string) => `/assets/${storeId}/upload`,
  },
  health: '/health',
  admin: {
    dashboard: '/admin/dashboard',
    stores: '/admin/stores',
    pendingStores: '/admin/stores/pending',
    approveStore: (id: string) => `/admin/stores/${id}/approve`,
    rejectStore: (id: string) => `/admin/stores/${id}/reject`,
    suspendStore: (id: string) => `/admin/stores/${id}/suspend`,
    users: '/admin/users',
    userDetails: (id: string) => `/admin/users/${id}`,
    subscriptions: '/admin/subscriptions',
    cancelSubscription: (id: string) => `/admin/subscriptions/${id}/cancel`,
    updateSubscription: (id: string) => `/admin/subscriptions/${id}`,
    orders: '/admin/orders',
    plans: '/plans/all',
    createPlan: '/plans',
    updatePlan: (id: string) => `/plans/${id}`,
    deletePlan: (id: string) => `/plans/${id}`,
  },
} as const;
